# Generated by Django 5.2.5 on 2025-08-07 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='family_name',
            new_name='family',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='given_name',
            new_name='given',
        ),
    ]
