# Generated by Django 5.2.5 on 2025-08-08 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_family_name_patient_family_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temporaryaccesstoken',
            old_name='expiry_time',
            new_name='expires_at',
        ),
        migrations.RemoveField(
            model_name='temporaryaccesstoken',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='temporaryaccesstoken',
            name='patient',
        ),
        migrations.AddField(
            model_name='temporaryaccesstoken',
            name='patient_id',
            field=models.CharField(default='UNKNOWN', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='temporaryaccesstoken',
            name='token',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
